default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: develop-user3
  password: password3
  host: localhost

development:
  primary:
    <<: *default
    database: example_development

  queue:
    <<: *default
    database: example_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: example_test

production:
  primary:
    <<: *default
    database: example_production

  queue:
    <<: *default
    database: example_production_queue
    migrations_paths: db/queue_migrate